name: soulspeak
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_serializable: ^6.6.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  translator: ^1.0.3+1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.4.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  diacritic: ^0.1.3
  zego_uikit_prebuilt_call: ^4.16.23
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6 
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
  assets:
    #- assets/intents.json <- removido
